## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer -264.00/259.00  -257.00/256.00  -277.00/261.00
accel_x_min: 264.00
accel_x_max: 259.00
accel_y_min: -257.00
accel_y_max: 256.00
accel_z_min: -277.00
accel_z_max: 261.00

### magnetometer
# standard calibration -586.00/708.00  -623.00/661.00  -482.00/628.00
magn_x_min: -586.00
magn_x_max: 708.00
magn_y_min: -623.00
magn_y_max: 661.00
magn_z_min: -482.00
magn_z_max: 628.00

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [87.7551, -29.4264, 70.0805]
magn_ellipsoid_transform: [[0.764302, 0.0426026, -0.0104929], [0.0426026, 0.813411, 0.0428809], [-0.0104929, 0.0428809, 0.990143]]

# AHRS to robot calibration
imu_yaw_calibration: 0

### gyroscope
gyro_average_offset_x: -42.04
gyro_average_offset_y: -1.89
gyro_average_offset_z: -10.53
